---
strategy: static
no_screen_padding: 'no'
dark_mode: 'no'
static_data: ''
polling_verb: get
polling_url: ''
polling_headers: ''
polling_body: ''
id: 23139
custom_fields:
- keyname: author_bio
  name: About This Plugin
  field_type: author_bio
  category: life,images
  description: Winnie the Pooh quotes. Curated by Jasper, @jasper on TRMNL Discord.
  email_address: info@jaspervandermeij.com
name: Winnie the Pooh Quotes
refresh_interval: 240
